version: '3'

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
  web:
    restart: always
    env_file: .env
    build: ./
    command: bash -c "python manage.py collectstatic --noinput && gunicorn echangarro.wsgi:application --bind 0.0.0.0:3500"
    volumes:
      - .:/src
    ports:
      - 3500:3500
    environment:
      - DEBUG=$DEBUG
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - SECRET_KEY=$SECRET_KEY
    depends_on:
      - db
  nginx:
    image: nginx:1.14.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:3000
    depends_on:
      - web

volumes:
  pgdata:
