# Generated by Django 2.1.4 on 2019-01-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.TextField(max_length=110)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('SOBRE CHICO', 'SOBRE CHICO'), ('SOBRE MEDIANO', 'SOBRE MEDIANO'), ('SOBRE GRANDE', 'SOBRE GRANDE'), ('CAJA EXTRA CHICA', 'CAJA EXTRA CHICA'), ('CAJA CHICA', 'CAJA CHICA'), ('CAJA MEDIANA', 'CAJA MEDIANA'), ('CAJA GRANDE', 'CAJA GRANDE'), ('CAJA EXTRA GRANDE', 'CAJA EXTRA GRANDE'), ('DIMENSIONES EXTRAORDINARIAS', 'DIMENSIONES EXTRAORDINARIAS')], default='CAJA CHICA', max_length=110)),
                ('dimensiones_maximas', models.CharField(max_length=110)),
                ('envio_por', models.CharField(choices=[('DHL', 'DHL'), ('ESTAFETA', 'ESTAFETA'), ('UPS', 'UPS'), ('CORREO NACIONAL', 'CORREO NACIONAL')], default='DHL', max_length=110)),
                ('costo_envio_nacional', models.IntegerField()),
                ('necesario_cotizar', models.BooleanField(default=False)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de envio',
                'verbose_name_plural': 'Categorias de envios',
            },
        ),
    ]
