# Generated by Django 2.1.4 on 2019-01-09 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=220)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('aviso_privacidad', models.TextField(blank=True, null=True)),
                ('terminos_y_condiciones', models.TextField(blank=True, null=True)),
                ('correo_contacto', models.CharField(blank=True, max_length=110, null=True)),
                ('direccion_tienda', models.TextField(blank=True, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=110, null=True)),
                ('logo_tienda', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='')),
                ('banner_tienda', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de tienda',
                'verbose_name_plural': 'Configuracion de datos de tienda',
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_contacto', models.CharField(blank=True, max_length=110, null=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono_de_contacto', models.CharField(blank=True, max_length=110, null=True)),
                ('mensaje', models.TextField()),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('usuario_registrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto de cliente',
                'verbose_name_plural': 'Mensajes enviados por clientes',
            },
        ),
    ]
