# Generated by Django 2.1.4 on 2019-01-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosDisponibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_disponible', models.BooleanField(default=True)),
                ('perfil_disponible', models.BooleanField(default=True)),
                ('ordenes', models.BooleanField(default=True)),
                ('cotizacion_envios', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicios disponibles',
                'verbose_name_plural': 'Servicio disponibles',
            },
        ),
    ]
