# Generated by Django 2.1.4 on 2019-01-09 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=220)),
                ('colonia', models.CharField(max_length=220)),
                ('municipio', models.CharField(max_length=220)),
                ('codigo_postal', models.IntegerField()),
                ('estado', models.CharField(choices=[('Distrito Federal', 'Distrito Federal'), ('Jalisco', 'Jalisco'), ('Michoacan', 'Michoacan')], max_length=110)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Direccion de usuario',
                'verbose_name_plural': 'Direcciones de usuario',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=220, null=True)),
                ('apeidos', models.CharField(blank=True, max_length=220, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_de_perfil', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='')),
                ('correo_confirmado', models.BooleanField(default=False)),
                ('pwd_comprometido', models.BooleanField(default=False)),
                ('uuid_de_confirmacion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='ProductoDeseado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Perfil'),
        ),
    ]
