# Generated by Django 2.1.4 on 2019-01-09 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=220)),
                ('colonia', models.CharField(max_length=220)),
                ('municipio', models.CharField(max_length=220)),
                ('codigo_postal', models.IntegerField()),
                ('estado', models.CharField(max_length=110)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Direccion de envio para orden',
                'verbose_name_plural': 'Direcciones de envio para ordenes',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('TENTATIVA', 'TENTATIVA'), ('INICIADO', 'INICIADO'), ('PAGADO', 'PAGADO'), ('ENTREGADO', 'ENTREGADO'), ('CANCELADO', 'CANCELADO'), ('DEVUELTO', 'DEVUELTO')], default='INICIADO', max_length=110)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.fields.CharField, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compra',
            },
        ),
        migrations.CreateModel(
            name='ProductoEnOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Producto en orden',
                'verbose_name_plural': 'Productos en ordenes',
            },
        ),
        migrations.AddField(
            model_name='direccionorden',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ordenes.Orden'),
        ),
    ]
