# Generated by Django 2.1.4 on 2019-01-09 05:38

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_de_desplegado', models.IntegerField()),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='')),
                ('leyenda', models.CharField(blank=True, max_length=110, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imagenes de producto',
            },
        ),
    ]
